from __future__ import annotations

from collections.abc import Iterable, Iterator
from http.cookiejar import Cookie, CookieJar

class BrowserCookieError(Exception): ...

class BrowserCookieLoader:
    def __init__(self, cookie_files: Iterable[str] | None = ...) -> None: ...
    def find_cookie_files(self) -> Iterator[str]: ...
    def get_cookies(self) -> Iterator[Cookie]: ...
    def load(self) -> CookieJar: ...

class ChromeBased(BrowserCookieLoader):
    def get_cookies(self) -> Iterator[Cookie]: ...

class Chrome(ChromeBased):
    def __str__(self) -> str: ...

class Brave(ChromeBased):
    def __str__(self) -> str: ...

class Chromium(ChromeBased):
    def __str__(self) -> str: ...

class Vivaldi(ChromeBased):
    def __str__(self) -> str: ...

class Edge(ChromeBased):
    def __str__(self) -> str: ...

class EdgeDev(ChromeBased):
    def __str__(self) -> str: ...

class Firefox(BrowserCookieLoader):
    def __str__(self) -> str: ...
    def parse_profile(self, profile: str) -> str: ...
    def find_default_profile(self) -> list[str]: ...

class Safari(BrowserCookieLoader):
    def __str__(self) -> str: ...
    def find_cookie_files(self) -> Iterator[str]: ...

def create_local_copy(cookie_path: str, suffix: str = ...) -> Iterator[str]: ...
def create_cookie(
    host: str,
    path: str,
    secure: bool,
    expires: int | None,
    name: str,
    value: str,
) -> Cookie: ...
def brave(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def chrome(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def chromium(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def vivaldi(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def edge(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def edge_dev(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def firefox(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def safari(cookie_files: Iterable[str] | None = ...) -> CookieJar: ...
def load() -> CookieJar: ...
